# Using Bias

## Objectives

- Understand why using bias is necessary:
 - Learn a  function that doesn't need bias
 - Learning 2*x + 1, a function that needs bias to be correctly learned
 - Adding bias in the model

## Learn a  function that doesn't need bias: y = 2*x

<table style="float:left">
  <tr>
    <th>x</th>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <th>y</th>
    <td>2</td>
    <td>4</td>
    <td>6</td>
  </tr>
</table>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'0.10.0'

<img align="left" src="files/modified.png"> **Modified Code:** First learner compact code with the following changes:

* x, y, w are now matrices
* using tf.matmul instead of *

In [3]:
x = tf.constant([[1.],[2.],[3.]])
y = tf.constant([[2.],[4.],[6.]])

weight = tf.Variable([[0.]])

y_pred = tf.matmul(x, weight)

loss = (y - y_pred)**2

train_step = tf.train.GradientDescentOptimizer(0.05).minimize(loss)

sess = tf.Session()
sess.run(tf.initialize_all_variables())

for i in range(0,20):
    sess.run(train_step)

## Result

In [4]:
sess.run(y_pred)

array([[ 1.99999988],
       [ 3.99999976],
       [ 5.99999952]], dtype=float32)

Pretty good!

And the weight is:

In [5]:
sess.run(weight)

array([[ 1.99999988]], dtype=float32)

## Learning 2*x + 1, a function that needs bias to be correctly learned

<table style="float:left">
  <tr>
    <th>x</th>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <th>y</th>
    <td>3</td>
    <td>5</td>
    <td>7</td>
  </tr>
</table>

<img align="left" src="files/old.png"> **Same Code:** Only the y values are changed

In [6]:
import tensorflow as tf

x = tf.constant([[1.],[2.],[3.]])
y = tf.constant([[3.],[5.],[7.]])

weight = tf.Variable([[0.]])

y_pred = tf.matmul(x, weight)

loss = (y - y_pred)**2

train_step = tf.train.GradientDescentOptimizer(0.05).minimize(loss)

sess = tf.Session()
sess.run(tf.initialize_all_variables())

for i in range(0,20):
    sess.run(train_step)

## Result

In [7]:
sess.run(y_pred)

array([[ 2.42857146],
       [ 4.85714293],
       [ 7.28571415]], dtype=float32)

In [8]:
sess.run(weight)

array([[ 2.42857146]], dtype=float32)

Not nearly as good as the first example

## Adding bias to the model

<img align="left" src="files/modified.png"> **Modified Code:** Adding bias


In [9]:
x = tf.constant([[1.],[2.],[3.]])
y = tf.constant([[3.],[5.],[7.]])

weight = tf.Variable([[0.]])

# added here
bias = tf.Variable([[0.]]) 

y_pred = tf.matmul(x, weight) + bias # and here !

loss = (y - y_pred)**2

train_step = tf.train.GradientDescentOptimizer(0.05).minimize(loss)

sess = tf.Session()
sess.run(tf.initialize_all_variables())

for i in range(0,200):
    sess.run(train_step)

## Result

In [11]:
sess.run(y_pred)

array([[ 2.99996376],
       [ 4.99999237],
       [ 7.00002193]], dtype=float32)

In [12]:
sess.run(weight)

array([[ 2.00002885]], dtype=float32)

In [13]:
sess.run(bias)

array([[ 0.99993491]], dtype=float32)

So the function learned is: y = 2.00002885*x + 0.99993509. Pretty close!